language: java
sudo: false
script:
- sudo apt install pastebinit -y
- wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
- git config --global --unset core.autocrlf
- travis_wait 30 java -jar BuildTools.jar &> log.txt
- pastebinit log.txt
- ls
