language: java
sudo: false
script:
- sudo apt install pastebinit -y
- wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
- travis_wait 30 java -jar BuildTools.jar &> log.txt
- pastebinit log.txt
- ls
- cd Spigot/Spigot-Server/target
- curl --upload-file ./spigot-1.12.2-R0.1-SNAPSHOT.jar https://transfer.sh/spigot-1.12.2-R0.1-SNAPSHOT.jar
