language: java
sudo: false
script:
- wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
- git config --global --unset core.autocrlf
- travis_wait 30 java -jar BuildTools.jar
